### ISSUE TITLE
More companies

### ISSUE THREAD

**Issue by AllaKaplia** [readytotouch/gocompanies#16]
- [ ] 1. https://www.reddit.com/r/golang/comments/wg7ovf/what_companies_are_using_golang_and_have_source/
- [ ] 2. https://www.reddit.com/r/golang/comments/p3pfcu/what_are_startups_companies_doing_some_amazing/
- [ ] 3. KOHO Financial https://app.otta.com/jobs/S3p4c1rQ
- [ ] 4. Cuvva  https://app.otta.com/jobs/cQvej3S6
- [x] 5. Okta https://app.otta.com/jobs/QcMdOhR_
- [ ] 6. BloomReach https://app.otta.com/jobs/TzJIN0N0
- [x] 7. Wise https://app.otta.com/jobs/UVRcHQhe
- [x] 8. Checkout.com https://www.linkedin.com/jobs/view/3920739722/ https://app.otta.com/jobs/YtWKA6Og
- [ ] 9. ZeptoLab https://app.otta.com/jobs/KdR20rBv https://startup.jobs/senior-golang-developer-belgrade-remote-zeptolab-5458820
- [ ] 10. Lemfi https://app.otta.com/jobs/i06lYUah
- [x] 11. Atom bank https://www.linkedin.com/jobs/view/3921514553/
- [ ] 12. VDart https://www.linkedin.com/jobs/view/3922878133/
- [ ] 13. Globant https://www.linkedin.com/jobs/view/3921508141/
- [ ] 14. Exarca https://www.linkedin.com/jobs/view/3919343470/
- [ ] 15. iCode Technologies https://www.linkedin.com/jobs/view/3919341257
- [x] 16. Samsung https://www.linkedin.com/jobs/view/3919334242/
- [ ] 17. Dabster https://www.linkedin.com/jobs/view/3919313153/
- [ ] 18. Athsai https://www.linkedin.com/jobs/view/3922753758/
- [ ] 19. Voltron Data https://www.linkedin.com/jobs/view/3922273915/
- [ ] 20. Mobiweb https://www.linkedin.com/jobs/view/3862640449/
- [ ] 21. Xenoss https://www.linkedin.com/jobs/view/3921850439/ (Україна, Ukraine)
- [ ] 22. WE ARE META https://www.linkedin.com/jobs/view/3921718971/
- [ ] 23. Proofpoint https://www.linkedin.com/jobs/view/3797062001/
- [ ] 24. Pyramid Consulting, Inc https://www.linkedin.com/jobs/view/3917536275/
- [ ] 25. ZeptoLab https://www.linkedin.com/jobs/view/3921349045/
- [ ] 26. Axel Springer https://www.linkedin.com/jobs/view/3919642961/
- [ ] 27. team.it https://www.linkedin.com/jobs/view/3917521602/
- [ ] 28. ALTEN Polska https://www.linkedin.com/jobs/view/3920852627/
- [ ] 29. Sherpa 6, Inc. https://www.linkedin.com/jobs/view/3920523883/
- [ ] 30. Devoteam https://www.linkedin.com/jobs/view/3918953647/
- [ ] 31. Capital One https://www.linkedin.com/jobs/view/3918937743/
- [ ] 32. Seldon https://www.linkedin.com/jobs/view/3920199344/ https://startup.jobs/software-engineer-golang-romania-remote-seldon-5434830
- [ ] 33. Intelygenz https://www.linkedin.com/jobs/view/3918870577/
- [ ] 34. Tigerhall https://www.linkedin.com/jobs/view/3918805463/
- [ ] 35. Encora Inc. https://www.linkedin.com/jobs/view/3918603249/
- [ ] 36. Third Eye Software https://www.linkedin.com/jobs/view/3919433241/
- [ ] 37. Paralucent https://www.linkedin.com/jobs/view/3919423951/
- [ ] 38. AssureSoft https://www.linkedin.com/jobs/view/3919412735/
- [ ] 39. Equifax https://www.linkedin.com/jobs/view/3919408607/
- [ ] 40. Solugenix https://www.linkedin.com/jobs/view/3918408821/
- [ ] 41. Satwic Inc https://www.linkedin.com/jobs/view/3915787616/
- [ ] 42. Vivid Money https://www.linkedin.com/jobs/view/3918192159/
- [ ] 43. GoCode Pte Ltd https://www.linkedin.com/jobs/view/3918331493/
- [ ] 44. Voltron Data https://www.linkedin.com/jobs/view/3922273915/
- [ ] 45. Outreach https://startup.jobs/staff-software-engineer-backend-golang-or-rubyrails-outreach_io-5348304
- [ ] 46. Bitpanda https://startup.jobs/senior-backend-engineer-golang-bitpanda-2-5407653
- [ ] 47. Pure Integration https://startup.jobs/golang-developer-remote-pure-integration-5430836
- [ ] 48. Urban Sports Club https://startup.jobs/senior-backend-engineer-all-genders-golang-urban-sports-club-5434305
- [ ] 49. Tucows https://startup.jobs/software-engineer-golang-tucows-5335098
- [ ] 50. Zuva https://startup.jobs/senior-software-developer-golang-contract-zuva-5335113
- [ ] 51. Lightspeed Systems https://startup.jobs/full-stack-software-engineer-go-golang-lightspeed-systems-5330906
- [ ] 52. https://startup.jobs/senior-golang-engineer-rvo-health-5318028
- [ ] 53. https://startup.jobs/senior-software-engineer-golang-cross-river-5280320
- [ ] 54. https://startup.jobs/senior-golang-engineer-prysm-offchainlabs-5279396
- [ ] 55. https://startup.jobs/senior-backend-engineer-golang-cloudfactory-5261897
- [ ] 56. https://startup.jobs/senior-golang-engineer-fmd-80-100-valbonne-hybrid-work-smg-swiss-marketplace-group-5073709
- [ ] 57. https://startup.jobs/software-engineer-in-test-golang-required-chainlink-labs-5029571
- [ ] 58. https://startup.jobs/senior-software-engineer-golang-wallex-4938321
- [ ] 59. https://startup.jobs/senior-software-engineer-golang-zartis-4920053
- [ ] 60. https://startup.jobs/senior-software-engineer-golang-vancouver-geocomply-4865715
- [ ] 61. https://startup.jobs/software-engineer-golang-anaplan-4834946
- [ ] 62. https://startup.jobs/staff-software-engineer-cloud-architect-golang-ruby-wallarm-5244680
- [ ] 63. https://startup.jobs/senior-software-engineer-golang-sovtech-4817114
- [ ] 64. Bosch https://www.linkedin.com/jobs/view/3921389394/
- [ ] 65. Verdant Infotech Solutions https://www.linkedin.com/jobs/view/3924322670/
- [ ] 66. Cint https://app.otta.com/jobs/CNZrs4TQ
- [x] 67. Monzo https://app.otta.com/jobs/ZwnXtENr
- [ ] 68. KOHO Financial https://app.otta.com/jobs/oAIXIsbI
- [ ] 69. Aescape https://www.linkedin.com/jobs/view/3790087744/
- [ ] 70. Runway https://app.otta.com/jobs/934uiuFI
- [ ] 71. Fujitsu https://www.linkedin.com/jobs/view/3925843970/
- [ ] 72. gridX https://www.linkedin.com/jobs/view/3924968033/
- [ ] 73. Tech Mahindra https://www.linkedin.com/jobs/view/3921625702/
- [ ] 74. Test Triangle https://www.linkedin.com/jobs/view/3921604918/
- [ ] 75. Cinemo https://www.linkedin.com/jobs/view/3921611198/
- [ ] 76. SUSE https://www.linkedin.com/jobs/view/3921146044/
- [ ] 77.

**Comment by YaroslavPodorvanov** [comment]
- [ ]  Q1 Technologies, Inc. https://www.linkedin.com/jobs/view/3926775800/
- [ ]  Vertex Elite LLC https://www.linkedin.com/jobs/view/3927033294/
- [ ]  Verdant Infotech Solutions https://www.linkedin.com/jobs/view/3927028797/
- [ ]  Fingerprint https://www.linkedin.com/jobs/view/3927027145/
- [ ]  TechOne https://www.linkedin.com/jobs/view/3926375445/
- [ ]  Kumaran Systems https://www.linkedin.com/jobs/view/3926369877/
- [ ]  Multivision Consulting https://www.linkedin.com/jobs/view/3926352999/
- [x]  Dojo https://www.linkedin.com/jobs/view/3926951138/
- [ ]  Data Concepts https://www.linkedin.com/jobs/view/3926940730/
- [x]  American Express https://www.linkedin.com/jobs/view/3926321626/
- [ ]  Kforce Inc https://www.linkedin.com/jobs/view/3926313252/
- [ ]  ACL Digital https://www.linkedin.com/jobs/view/3926917484/
- [ ]  Snowflake https://www.linkedin.com/jobs/view/3926599919/
- [ ]  Capco https://www.linkedin.com/jobs/view/3926908487/
- [ ]  Creative Fabrica https://www.linkedin.com/jobs/view/3926233906/
- [ ]  Exness https://www.linkedin.com/jobs/view/3926235610/
- [ ]  Z3 Works https://www.linkedin.com/jobs/view/3925336525/
- [ ]  Kablamo https://www.linkedin.com/jobs/view/3926180407/
- [ ]  Trideca https://www.linkedin.com/jobs/view/3926160243/
- [ ]  Centraprise https://www.linkedin.com/jobs/view/3922058959/
- [ ]  Aiven https://www.linkedin.com/jobs/view/3925666055/
- [ ]  KCS iT https://www.linkedin.com/jobs/view/3921640220/
- [ ]  HCLTech https://www.linkedin.com/jobs/view/3926817022/
- [ ]  Concord IT Systems https://www.linkedin.com/jobs/view/3926797530/
- [ ]  Blacklane https://app.otta.com/jobs/iCL5dUoY
- [ ]  Macquarie Group https://www.linkedin.com/jobs/view/3929225934/
- [ ]  Apolis https://www.linkedin.com/jobs/view/3923153491/
- [ ]  Clinia https://www.linkedin.com/jobs/view/3928917898/
- [ ]  Nearform https://www.linkedin.com/jobs/view/3928612807/
- [ ]  CGI https://www.linkedin.com/jobs/view/3928568488/
- [ ]  POWER IT SERVICES https://www.linkedin.com/jobs/view/3928395155/
- [ ]  JPMorgan Chase & Co. https://www.linkedin.com/jobs/view/3922430974/
- [x]  Mastercard https://www.linkedin.com/jobs/view/3928338037/
- [ ]  Steneral Consulting https://www.linkedin.com/jobs/view/3928317081/
- [ ]  Photon https://www.linkedin.com/jobs/view/3927619982/
- [ ]  Integer Consulting https://www.linkedin.com/jobs/view/3927617186/
- [ ]  TechOne https://www.linkedin.com/jobs/view/3926375445/
- [ ]  Proof Technology https://app.otta.com/jobs/-NxdgPLa
- [ ]  The Hotels Network https://app.otta.com/jobs/oEDhs7AR
- [ ]  PT Bank Multiarta Sentosa Tbk (Bank MAS) https://www.linkedin.com/jobs/view/3934497300/
- [ ]  Regrello https://app.otta.com/jobs/lhF7OIPi
- [ ]  Fonoa https://app.otta.com/jobs/phGYrTHK
- [x]  Okta https://app.otta.com/jobs/FtbF4gpB
